apiVersion: v1
kind: Pod
metadata:
  name: temp-storage-pod
spec:
  containers:
    - name: app-container
      image: nginx
      volumeMounts:
        - mountPath: /tmp/data
          name: temp-storage
  volumes:
    - name: temp-storage
      emptyDir: {}
