apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
    - name: app-container
      image: nginx
      volumeMounts:
        - mountPath: /mnt/data
          name: host-data
  volumes:
    - name: host-data
      hostPath:
        path: /mnt/data
        type: Directory
