apiVersion: v1
kind: Service
metadata:
  # the name is db because the db worker expects this name
  # to connect to it hardcoded the query connection string
  name: db
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  # node that this selector section is really important
  # because it is what links the service to the pod
  selector:
    name: postgres-pod
    app: demo-voting-app
