#NOTE: Alternatively:
# kubectl create role dev \
# --verb=list --verb=get --verb=create --verb=update --verb=delete \
# --resource=pods \
# --namespace=<namespace>
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["ConfigMap"]
  verbs: ["create"]
