#NOTE: Alternatively:
# kubectl create rolebinding dev-user-binding \
# --role=dev \
# --user=dev-user \
# --namespace=default
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  metadata: dev-user-role-binding
subjects:
- kind: User
  name: dev-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io
