apiVersion: v1
kind: Pod
metadata:
  name: option-one
spec:
  containers:
    - name: app-container
      image: your-app-image
      envFrom:
        - configMapRef:
            name: app-config
---
apiVersion: v1
kind: Pod
metadata:
  name: option-two
spec:
  containers:
    - name: app-container
      image: your-app-image
      env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATABASE_HOST
