apiVersion: v1
kind: Pod
metadata:
  name: option-one
spec:
  containers:
    - name: app-container
      image: your-app-image
      envFrom:
        - secretRef:
            name: app-secret
---
apiVersion: v1
kind: Pod
metadata:
  name: option-two
spec:
  containers:
    - name: app-container
      image: your-app-image
      env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DATABASE_PASSWORD
